### ISSUE TITLE
新手， 需要指教。 

### ISSUE THREAD

**Issue by cybershan** [tencentyun/TWebLive#11]
我用 npm i tweblive --save  后， 在当前文件夹里多了个TWebLive。  是不是修改里面的 Public/index.html就可以做出类似下面效果的互动页面？  

https://webim-1252463788.cos.ap-shanghai.myqcloud.com/tweblivedemo/index.html

非常希望有个Sample给新手学习。

**Comment by yangq1990** [comment]
请参考一分钟跑通系列哈：https://cloud.tencent.com/document/product/269/47959

**Comment by cybershan** [comment]
非常感谢！ @yangq1990     

刚试了一下， 的确很快可以用了。   另外想问这个组件是否可以直接对接云直播呢？  不用使用实时音视频。

**Comment by yangq1990** [comment]
可以的，tweblive可以作为纯播放端。只需要创建 player ，并按照规则拼接url，就能快速地用于微信h5分享观看等

参考下api手册： https://webim-1252463788.cos.ap-shanghai.myqcloud.com/tweblive/TWebLive.html#.createPlayer
