### ISSUE TITLE
pusher摄像头预览正常，player看到的画面左右反的，怎么调整

### ISSUE THREAD

**Issue by keyzjj** [tencentyun/TWebLive#21]
pusher摄像头预览正常，player看到的画面左右反的，怎么调整

**Comment by yangq1990** [comment]
感谢关注，下一版本 tweblive sdk 会增加一个 `mirror` 属性，控制视频显示是否为镜像

**Comment by yangq1990** [comment]
或者您可以通过css控制video，也能实现相同的效果

**Comment by keyzjj** [comment]
谢谢谢谢  问题已解决
