### ISSUE TITLE
两个问题请教

### ISSUE THREAD

**Issue by conghuiw** [tencentyun/TWebLive#30]
问题1：

tim.js 中的这端代码（第2行）需要改吗？
const SDKAppID =  window.genTestUserSig('').SDKAppID

问题2：
请问该直播间创建的直播间是实时音视频TRTC主播房间吗？

**Comment by Tencent-Alice** [comment]
您好，关于您的描述
 1.tim.js 中的这端代码（第2行）需要改吗？
const SDKAppID = window.genTestUserSig('').SDKAppID
这个不需要改的，您直接在genTestUserSig里面讲SDKAPPID改成您的应用信息即可

2请问该直播间创建的直播间是实时音视频TRTC主播房间吗？
是的
技术问题 欢迎交流 Q2562367495 注明来意

**Comment by conghuiw** [comment]
感谢回复，关闭issue
