### ISSUE TITLE
使用pusher屏幕共享startpush操作失败

### ISSUE THREAD

**Issue by conghuiw** [tencentyun/TWebLive#32]
你好，感谢提供sdk，尝试使用pusher进行屏幕共享，请帮忙查看下，谢谢。

【初始化】
 const pusher = Vue.prototype.TWebLive.createPusher({
        userID: this.chatInfo.userId,
        screenCapture:true
      })

【setrenderview】
 this.pusher.setRenderView({
        elementID: 'video-container',
        screenProfile: '360p', // 默认
        systemAudio: false // 采集系统声音，默认不采集
      }).then(()

屏幕共享在startpush这步pusher.startPush(url)报错：
      let userSig = this.chatInfo.userSig
      let SDKAppID = this.chatInfo.sdkAppID
      let liveDomainName = this.chatInfo.liveDomainName //'3891.liveplay.myqcloud.com' 配置的推流域名
      let streamID = `${SDKAppID}_${this.chatInfo.groupId}_${userID}_main` //sdkappid_roomid_userid_main
      let url = `room://livedomainname=${liveDomainName}&sdkappid=${SDKAppID}&roomid=${this.chatInfo.groupId}&userid=${this.chatInfo.userId}&usersig=${userSig}&streamid=${streamID}`
      this.ready = true
      this.startAnimation()
      this.pusher.startPush(url).then(()

【报错信息】
webpack-internal:///./src/components/pusher/pusher.js:358 demo pusher | startPush | failed TypeError: this._client.setDefaultMuteRemoteStreams is not a function
    at eval (webpack-internal:///./node_modules/tweblive/tweblive.js:1)
    at l (webpack-internal:///./node_modules/tweblive/tweblive.js:1)
    at Generator.eval [as _invoke] (webpack-internal:///./node_modules/tweblive/tweblive.js:1)
    at Generator.eval [as next] (webpack-internal:///./node_modules/tweblive/tweblive.js:1)
    at a (webpack-internal:///./node_modules/tweblive/tweblive.js:1)
    at s (webpack-internal:///./node_modules/tweblive/tweblive.js:1)
    at eval (webpack-internal:///./node_modules/tweblive/tweblive.js:1)
    at new Promise (<anonymous>)
    at eval (webpack-internal:///./node_modules/tweblive/tweblive.js:1)
    at eval (webpack-internal:///./node_modules/tweblive/tweblive.js:1)

还有一个疑问就是下面这条要求是强制必须的吗：
 userID: 'screen-' + 'your userID', // 屏幕分享 Pusher 的 ID，以 'screen-' 开头

**Comment by conghuiw** [comment]
=============添加完整log====================
Some messages have been moved to the Issues panel.
localhost/:11 The key "mininmum-scale" is not recognized and ignored.
webpack-internal:///./node_modules/webpack/hot/log.js:24 [HMR] Waiting for update signal from WDS...
lib-generate-test-usersig.min.js:1 sdkAppID=1400473953 key=ee85e933f05525b2981d49d60666b94187a70608f7721fd9aa153bbcd8f2a578 userID= expire=604800
lib-generate-test-usersig.min.js:1 ret=eJwtzMEKgkAUheF3ueuQOzpOJrQIW6i0yqC2yUx1ddTJkRSid29Ql*c78H-hciq8j*ohBt9D2MybpGoHetDMq1lZ340hCTHjiHwb7MJgeQZqlFPBGPKIh2JRNRnqnQuHiGuDni6IDbM274qpraL3mNqsrPw60MdXfh7TxJZ41dQlt4Pm2R5*f6NNL4w_
lib-generate-test-usersig.min.js:1 sdkAppID=1400473953 key=ee85e933f05525b2981d49d60666b94187a70608f7721fd9aa153bbcd8f2a578 userID= expire=604800
lib-generate-test-usersig.min.js:1 ret=eJwtzMEKgkAUheF3ueuQOzpOJrQIW6i0yqC2yUx1ddTJkRSid29Ql*c78H-hciq8j*ohBt9D2MybpGoHetDMq1lZ340hCTHjiHwb7MJgeQZqlFPBGPKIh2JRNRnqnQuHiGuDni6IDbM274qpraL3mNqsrPw60MdXfh7TxJZ41dQlt4Pm2R5*f6NNL4w_
webpack-internal:///./node_modules/tim-js-sdk/tim-js.js:1 TIM 17:27:36.609:TIM.VERSION: 2.9.1
webpack-internal:///./node_modules/tweblive/tweblive.js:1 TWebLive Version: 1.1.1
lib-generate-test-usersig.min.js:1 sdkAppID=1400473953 key=ee85e933f05525b2981d49d60666b94187a70608f7721fd9aa153bbcd8f2a578 userID= expire=604800
lib-generate-test-usersig.min.js:1 ret=eJyrVgrxCdYrSy1SslIy0jNQ0gHzM1NS80oy0zLBwlCx4pTsxIKCzBQlK0MTAwMTc2NLU2OITElmbipQ1MzQ0MDEwsTUHCKaWlGQWQQUNwMKGhhAzchMBxoYHmTsnpwb5G3sWWGR6lOSVFwRmGJsnu9X6ZcfVpTmXBoeYFBlkubsFhGSbKtUCwCUPC9L
webpack-internal:///./node_modules/tweblive/tweblive.js:1 TWebLive v1.1.0起，createIM 前接入侧需要手动安装依赖 tim-js-sdk，详细请参考：https://webim-1252463788.cos.ap-shanghai.myqcloud.com/tweblive/TWebLive.html
value @ webpack-internal:///./node_modules/tweblive/tweblive.js:1
webpack-internal:///./node_modules/tim-js-sdk/tim-js.js:1 TIM 17:27:36.640:TIM.create
webpack-internal:///./node_modules/tim-js-sdk/tim-js.js:1 TIM 17:27:36.644:SinglyLinkedList init MAX_LENGTH=100
webpack-internal:///./node_modules/tim-js-sdk/tim-js.js:1 TIM 17:27:36.646:SinglyLinkedList init MAX_LENGTH=100
webpack-internal:///./node_modules/tim-js-sdk/tim-js.js:1 TIM 17:27:36.647:SDK instanceID:ba30999edbeca55a7a3c4627e1bc8173 oversea:false inMiniApp:false, SDKAppID:1400473953, UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75
webpack-internal:///./node_modules/tim-js-sdk/tim-js.js:1 TIM 17:27:36.648:TIM.create ok
webpack-internal:///./node_modules/tim-js-sdk/tim-js.js:1 
 ________  ______  __       __  __       __  ________  _______
|        \|      \|  \     /  \|  \  _  |  \|        \|       \
 \$$$$$$$$ \$$$$$$| $$\   /  $$| $$ / \ | $$| $$$$$$$$| $$$$$$$\
   | $$     | $$  | $$$\ /  $$$| $$/  $\| $$| $$__    | $$__/ $$
   | $$     | $$  | $$$$\  $$$$| $$  $$$\ $$| $$  \   | $$    $$
   | $$     | $$  | $$\$$ $$ $$| $$ $$\$$\$$| $$$$$   | $$$$$$$\
   | $$    _| $$_ | $$ \$$$| $$| $$$$  \$$$$| $$_____ | $$__/ $$
   | $$   |   $$ \| $$  \$ | $$| $$$    \$$$| $$     \| $$    $$
    \$$    \$$$$$$ \$$      \$$ \$$      \$$ \$$$$$$$$ \$$$$$$$


webpack-internal:///./node_modules/tim-js-sdk/tim-js.js:1 IM 智能客服，随时随地解决您的问题 →_→ https://cloud.tencent.com/act/event/smarty-service?from=im-doc
webpack-internal:///./node_modules/tim-js-sdk/tim-js.js:1 
参考以下文档，会更快解决问题哦！(#^.^#)

SDK 更新日志: https://cloud.tencent.com/document/product/269/38492

SDK 接口文档: https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/SDK.html

常见问题: https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/tutorial-01-faq.html

反馈问题？戳我提 issue: https://github.com/tencentyun/TIMSDK/issues

如果您需要在生产环境关闭上面的日志，请 tim.setLogLevel(1)

webpack-internal:///./node_modules/tim-js-sdk/tim-js.js:1 TIM 17:27:36.649:set level from 0 to 0
webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:8418 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:8428 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
sockjs.js?9be2:3002 WebSocket connection to 'wss://localhost:8080/sockjs-node/509/aytrl2mb/websocket' failed: WebSocket is closed before the connection is established.
WebSocketTransport.close @ sockjs.js?9be2:3002
lib-generate-test-usersig.min.js:1 sdkAppID=1400473953 key=ee85e933f05525b2981d49d60666b94187a70608f7721fd9aa153bbcd8f2a578 userID=admin expire=604800
lib-generate-test-usersig.min.js:1 ret=eJwtzF0LgjAYhuH-suOQTef8gA4NwoKGYse2zfmik2GWRvTfG*rhcz1wf1F5Kby3GlGKfA*jw7pBqmGCBlaupYFhP56yq60FiVJCMaZRkITB9kxglFNGCKYxZWRTtVgYnTOHGO8N0K46J20XqOpcEH3L5-tHvEQV9jw*5Vo*Mt4K3yzZtedlJI7o9wfT2TFb
webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/liveList/liveList.vue?vue&type=script&lang=js&:212 liveRoom创建成功 79001268
webpack-internal:///./node_modules/tweblive/tweblive.js:1 TWebLive v1.1.0起，createPusher 前接入侧需要手动安装依赖 trtc-js-sdk，详细请参考：https://webim-1252463788.cos.ap-shanghai.myqcloud.com/tweblive/TWebLive.html
value @ webpack-internal:///./node_modules/tweblive/tweblive.js:1
webpack-internal:///./node_modules/trtc-js-sdk/trtc.js:1 [17:27:45] <INFO> [s|undefined]  setScreenProfile "1080p"
webpack-internal:///./node_modules/tweblive/tweblive.js:1 TWebLive 17:27:45.124:Pusher._createScreenStream screenProfile: 1080p 
webpack-internal:///./node_modules/trtc-js-sdk/trtc.js:1 [17:27:45] <INFO> [s|undefined]  initialize stream audio: true screenAudio: false screen: true
webpack-internal:///./node_modules/trtc-js-sdk/trtc.js:1 [17:27:45] <INFO> getDisplayMedia with constraints: {"video":{"width":1920,"height":1080,"frameRate":5}}
webpack-internal:///./node_modules/trtc-js-sdk/trtc.js:1 [17:27:47] <INFO> getUserMedia with constraints: {"audio":{"sampleRate":48000,"channelCount":1},"video":false}
webpack-internal:///./node_modules/trtc-js-sdk/trtc.js:1 [17:27:47] <INFO> [s|undefined]  set video track contentHint to: detail
webpack-internal:///./node_modules/trtc-js-sdk/trtc.js:1 [17:27:47] <INFO> [s|undefined]  set video track contentHint to: detail
webpack-internal:///./node_modules/trtc-js-sdk/trtc.js:1 [17:27:47] <INFO> [s|undefined]  stream start to play with options: {"objectFit":"cover","muted":true}
webpack-internal:///./node_modules/trtc-js-sdk/trtc.js:1 [17:27:47] <INFO> [s|undefined]  stream - create VideoPlayer and play
webpack-internal:///./node_modules/trtc-js-sdk/trtc.js:1 [17:27:47] <INFO> [s|undefined]  stream - video player is starting playing
webpack-internal:///./node_modules/trtc-js-sdk/trtc.js:1 [17:27:47] <INFO> [s|undefined]  stream - create AudioPlayer and play
webpack-internal:///./node_modules/trtc-js-sdk/trtc.js:1 [17:27:47] <INFO> [s|undefined]  stream - audioElement setVolume to : 1
webpack-internal:///./node_modules/trtc-js-sdk/trtc.js:1 [17:27:47] <INFO> [s|undefined]  stream - audio player is starting playing
webpack-internal:///./src/components/pusher/pusher.js:263 demo pusher | setRenderView | ok
lib-generate-test-usersig.min.js:1 sdkAppID=1400473953 key=ee85e933f05525b2981d49d60666b94187a70608f7721fd9aa153bbcd8f2a578 userID=screen-admin expire=604800
lib-generate-test-usersig.min.js:1 ret=eJwtzL0OgjAYheF76az4USoFEgcNxpi44aBsxFb8aFpIC8afeO82wHiek7xfcj4VwVNakhEaAFmMG4U0Pd5xZHezUpplJTSa*XdCVV2HgmQhA2A8StfR9PSopdc4DIEljNNJ5atD6z32CDA3sPZxOBRl3uet2x0T3mqVD8qZVK2Gd31pqFafZmuvj4RH5X5Dfn*JVzQq
webpack-internal:///./node_modules/tweblive/tweblive.js:1 TWebLive 17:27:52.172:Pusher.startPush roomID:79001268 SDKAppID:1400473953 userID:screen-admin streamID:1400473953_79001268_screen-admin_main liveDomainName:
webpack-internal:///./node_modules/trtc-js-sdk/trtc.js:1 ******************************************************************************
webpack-internal:///./node_modules/trtc-js-sdk/trtc.js:1 *   欢迎使用 TRTC Web SDK - 腾讯云实时音视频通信
webpack-internal:///./node_modules/trtc-js-sdk/trtc.js:1 *   API 文档：https://trtc-1252463788.file.myqcloud.com/web/docs/index.html
webpack-internal:///./node_modules/trtc-js-sdk/trtc.js:1 *   版本更新日志：https://cloud.tencent.com/document/product/647/38958
webpack-internal:///./node_modules/trtc-js-sdk/trtc.js:1 *   反馈问题：https://github.com/tencentyun/TRTCSDK/issues
webpack-internal:///./node_modules/trtc-js-sdk/trtc.js:1 ******************************************************************************
webpack-internal:///./node_modules/trtc-js-sdk/trtc.js:1 [17:27:52] <INFO> TRTC Web SDK Version: 4.8.4
webpack-internal:///./node_modules/trtc-js-sdk/trtc.js:1 [17:27:52] <INFO> UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75
webpack-internal:///./node_modules/trtc-js-sdk/trtc.js:1 [17:27:52] <INFO> URL of current page: https://localhost:8080/#/pusher
webpack-internal:///./node_modules/trtc-js-sdk/trtc.js:1 [17:27:52] <INFO> [c|screen-admin]  using sdpSemantics: plan-b
webpack-internal:///./src/components/pusher/pusher.js:359 demo pusher | startPush | failed TypeError: this._client.setDefaultMuteRemoteStreams is not a function
    at eval (webpack-internal:///./node_modules/tweblive/tweblive.js:1)
    at l (webpack-internal:///./node_modules/tweblive/tweblive.js:1)
    at Generator.eval [as _invoke] (webpack-internal:///./node_modules/tweblive/tweblive.js:1)
    at Generator.eval [as next] (webpack-internal:///./node_modules/tweblive/tweblive.js:1)
    at a (webpack-internal:///./node_modules/tweblive/tweblive.js:1)
    at s (webpack-internal:///./node_modules/tweblive/tweblive.js:1)
    at eval (webpack-internal:///./node_modules/tweblive/tweblive.js:1)
    at new Promise (<anonymous>)
    at eval (webpack-internal:///./node_modules/tweblive/tweblive.js:1)
    at eval (webpack-internal:///./node_modules/tweblive/tweblive.js:1)
eval @ webpack-internal:///./src/components/pusher/pusher.js:359

**Comment by Tencent-Alice** [comment]
您好，根据您的描述  需要和您确认，SDK版本号和具体操作步骤，以便更好定位
技术问题 欢迎交流 Q2562367495 注明来意

**Comment by conghuiw** [comment]
> 您好，根据您的描述 需要和您确认，SDK版本号和具体操作步骤，以便更好定位
> 技术问题 欢迎交流 Q2562367495 注明来意

问题已解决，感谢回复
