### ISSUE TITLE
采集麦克风及屏幕分享视频流

### ISSUE THREAD

**Issue by conghuiw** [tencentyun/TWebLive#34]
DELETE

**Comment by conghuiw** [comment]
补充一下，我想实现的功能是，主播先用摄像头+麦克风推流，然后切换到屏幕共享画面+麦克风推流。
请问这个过程可以使用一个pusher对象来实现吗？观看端是否能自动动态切换，相当于一个音视频流 streamid，使用cdn观看一路画面

**Comment by Tencent-Alice** [comment]
您好，根据您的描述 参考https://cloud.tencent.com/document/product/647/34066 实现 
技术问题 欢迎交流 Q2562367495 注明来意
